# Scikit Learn

### Estrucutura básica
1. Carga de datos
2. Preprocesar datos
3. Entrenar modelo
4. Evaluar modelo
5. Hacer predicciones

### 1. Carga de datos

In [15]:
from sklearn.datasets import load_iris
iris = load_iris(as_frame=True)
iris['data'].head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
0,5.1,3.5,1.4,0.2
1,4.9,3.0,1.4,0.2
2,4.7,3.2,1.3,0.2
3,4.6,3.1,1.5,0.2
4,5.0,3.6,1.4,0.2


In [16]:
iris2 = load_iris()
iris2['data']

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [19]:
# arrays
X, y = iris2['data'], iris2['target']

### 2. Dividir el conjunto de prueba

In [20]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

### 2.1 Example

In [22]:
import numpy as np

# Example data
X_example = np.array([[1], [2], [3], [4], [5], [6], [7], [8], [9], [10]])
y_example = np.array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1])

# split data
X_train_ex, X_test_ex, y_train_ex, y_test_ex = train_test_split(X_example, y_example, test_size=0.2, random_state=42)

# print
print("X_train\n", X_train_ex)
print("X_test\n", X_test_ex)
print("y_train\n", y_train_ex)
print("y_test\n", y_test_ex)

X_train
 [[ 6]
 [ 1]
 [ 8]
 [ 3]
 [10]
 [ 5]
 [ 4]
 [ 7]]
X_test
 [[9]
 [2]]
y_train
 [1 0 1 0 1 0 0 1]
y_test
 [1 0]


### 3. Escalado de características

In [ ]:
# Normalizar y estandarizar
